### ISSUE TITLE
typo in the readme file.

### ISSUE THREAD

**Issue by johnda98** [allenjake440/NFL_Champion#1]
Web scraped ... scrapped ?   ;-)  

Excellent Repos Jake ...  

I see the three ML algo models you used.  yes py has a serious set of Data Science / ML libraries.

Google up Langchain's py libs for most LLMs, very powerful py libs for AI data feeding and chaining the prompt/response,  the Vector database after data splitting and custom prompt tuning - may be of serious interest to your study.

PS. If you also google up the best self-custody Crypto hardwallet.. the Ledger Nano.. (just dont buy one from amazon/ebay.. buy it DIRECT from manufacturer in Paris France).    I can arrange for some Bitcoin that has been saved for yourself and the infamous Snuffy.   ;-) and you can hold it and watch it grow as the USD$ gets smaller.. that makes Bitcoins 'bigger', of course.

Love,
Dad.

**Comment by allenjake440** [comment]
Ah yes, I'll fix that lol. Thanks.

Yea, I'll look into that. It's gonna be interesting to see what happens
with blockchain and crypto in the future.

Love,
Jake
